### ISSUE TITLE
Main Activity

### ISSUE THREAD

**Issue by YanKarloTeixeira** [anupomr/SeboApp#4]
- [ ] Define the best layout for the activity

- [ ] Implement the listing filter based on the same user's campus

- [ ] Implement the books search engine

#3

**Comment by haocencol** [comment]
Define the best layout for the activity
> Attach a file with the propose layout (e.g., screen shot)

Implement the listing filter based on the same user's campus
> Provide detail of the filter.

Implement the books search engine
> Provide details of the algorithm
